set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

# Set via command line: -DAX_RUNTIME_ROOT=/path/to/AX650_SDK
if(NOT DEFINED AX_RUNTIME_ROOT)
    message(FATAL_ERROR "AX_RUNTIME_ROOT must be set. Example: -DAX_RUNTIME_ROOT=/opt/AX650_SDK_V3.10.2")
endif()

set(AX_SDK_ROOT ${AX_RUNTIME_ROOT})
set(CMAKE_C_COMPILER   ${AX_SDK_ROOT}/bin/aarch64-none-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${AX_SDK_ROOT}/bin/aarch64-none-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
